# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c78184a9acbaf994c29f22a3e61b555e2f7e6f93e710b5599799405b83572ce286ddbe8ad6a8a30763d7ff6c6264512008636963d9d3f12b0d0959687dd9cfa1

test:
  secret_key_base: c4e2f7c938b6bd4fd3f29b68e57177ec6aa1bc47f22934b6b9adc2df874a15bdbf5b63bcb6abfa63d5d59af58cfa67d67e6a3be1c6c8c5523fee003187f3bac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
